name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: swift build --configuration release

      - name: Run unit and integration tests
        run: swift test --enable-code-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # For private repositories, set CODECOV_TOKEN in GitHub secrets
          fail_ci_if_error: true